/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: cf8d6c85d81314ae6e5a960fc05d775c)
interface __BaseEnv_Env {
	SHARES: KVNamespace;
	SHARE_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
