const NOTES_STORAGE_KEY = 'videoNotes:notes';
const METADATA_STORAGE_KEY = 'videoNotes:metadata';
const ENABLED_STORAGE_KEY = 'videoNotes:enabled';
const ZEN_MODE_STORAGE_KEY = 'videoNotes:zenMode';
const ANNOTATIONS_ENABLED_STORAGE_KEY = 'videoNotes:annotationsEnabled';
const PLACEMENT_STORAGE_KEY = 'videoNotes:placement';
const MD_EXPORT_ENABLED_STORAGE_KEY = 'videoNotes:mdExportEnabled';
const MD_TEMPLATE_STORAGE_KEY = 'videoNotes:mdTemplate';
const MD_TEMPLATE_VERSION_STORAGE_KEY = 'videoNotes:mdTemplateVersion';
const DELETE_HOLD_ENABLED_STORAGE_KEY = 'videoNotes:deleteHoldEnabled';
const FLASHCARDS_ENABLED_STORAGE_KEY = 'videoNotes:flashcardsEnabled';
const NEWTAB_FLASHCARDS_ENABLED_STORAGE_KEY = 'videoNotes:newTabFlashcardsEnabled';
const GEMINI_API_KEY_STORAGE_KEY = 'videoNotes:geminiApiKey';
const FLASHCARDS_CACHE_STORAGE_KEY = 'videoNotes:flashcardsCache';
const FLASHCARDS_DECK_SIZE = 12;
const FLASHCARDS_MIN_NOTES = 6;
const FLASHCARDS_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
const LEGACY_DEFAULT_MD_TEMPLATE = '[*video-title*](*youtube-url*)\n\n- *time-url*: *note*';
const DEFAULT_MD_TEMPLATE = `${LEGACY_DEFAULT_MD_TEMPLATE}\n*annotation-image*`;
const MD_TEMPLATE_VERSION = 2;
const HOLD_DURATION_MS = 2000;
const VIDEO_RENDER_BATCH_SIZE = 50;
const NOTE_RENDER_BATCH_SIZE = 50;
const SEARCH_DEBOUNCE_MS = 150;
const VIEW_NOTES = 'notes';
const VIEW_SETTINGS = 'settings';
const VIEW_CONTEXT_PAGE = 'page';
const SETTINGS_MESSAGE_STATES = ['settings-message--success', 'settings-message--error'] as const;
const START_PLACEMENT_MESSAGE = 'VIDEO_NOTES_START_PLACEMENT';

export {
    ANNOTATIONS_ENABLED_STORAGE_KEY,
    DEFAULT_MD_TEMPLATE,
    DELETE_HOLD_ENABLED_STORAGE_KEY,
    ENABLED_STORAGE_KEY,
    FLASHCARDS_CACHE_STORAGE_KEY,
    FLASHCARDS_CACHE_TTL_MS,
    FLASHCARDS_DECK_SIZE,
    FLASHCARDS_ENABLED_STORAGE_KEY,
    FLASHCARDS_MIN_NOTES,
    GEMINI_API_KEY_STORAGE_KEY,
    HOLD_DURATION_MS,
    LEGACY_DEFAULT_MD_TEMPLATE,
    MD_EXPORT_ENABLED_STORAGE_KEY,
    MD_TEMPLATE_STORAGE_KEY,
    MD_TEMPLATE_VERSION,
    MD_TEMPLATE_VERSION_STORAGE_KEY,
    METADATA_STORAGE_KEY,
    NOTE_RENDER_BATCH_SIZE,
    NEWTAB_FLASHCARDS_ENABLED_STORAGE_KEY,
    NOTES_STORAGE_KEY,
    PLACEMENT_STORAGE_KEY,
    SEARCH_DEBOUNCE_MS,
    SETTINGS_MESSAGE_STATES,
    START_PLACEMENT_MESSAGE,
    VIDEO_RENDER_BATCH_SIZE,
    VIEW_CONTEXT_PAGE,
    VIEW_NOTES,
    VIEW_SETTINGS,
    ZEN_MODE_STORAGE_KEY
};
